### ISSUE TITLE
Integration with notiwire

### ISSUE THREAD

**Issue by duvholt** [webkom/coffee#34]
Online Notifier uses data from [notiwire](https://github.com/appKom/notiwire) to display information about coffee etc.  https://passoa.online.ntnu.no/api/affiliation/abakus
At the moment Abakus' coffee data is cached with an unfortunate long timeout. I've started working on a better solution for this, but that's another story.

The question is really if you would be willing to integrate with our coffee notification API? This way the cache is automatically purged and there will be no need to keep polling your API. 
It's a simple [endpoint](https://github.com/appKom/notiwire/wiki/notipi#coffee) that you would send a single POST request to when a new coffee pot is ready.

I can submit a PR if there is any interest in this. :)

**Comment by eirsyl** [comment]
Green Light ✳️  Can you create a PR? 😄
